### ISSUE TITLE
Hello, your application is great, but the content it creates is too short.

### ISSUE THREAD

**Issue by KalvinThien** [zzzprojects/zzzcode.ai#3]
Hello, your application is great, but the content it creates is too short.

Can you let it break the code into small pieces?
That means every 1000 - 2000 tokens / 1 transfer, and transfer continuously until the original code that needs to be transferred runs out.
Thanks a lot

**Comment by JonathanMagnan** [comment]
Hello @KalvinThien ,

Allowing 16k model is in our plan. It will require people to log on to our website (when it will be available), so we can limit it per user.

The 16k model is twice the price of the 4k model, so that's why it's not enabled yet.

I will try to run some tests next week to see how much it will cost us if we enable it and switch from 4k to 16k depending on the number of tokens in the `Input`.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @KalvinThien ,

We enabled the temporary 16k, but I just noticed that was not your request at all.

My question for you is: In what way does transferring a small chunk of content over and over affect you? At this moment, we transfer the content as soon as we receive it from Chat GPT or Azure API.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
I will close this issue since there has been no answer since last week.

Best Regards,

Jon

**Comment by KalvinThien** [comment]
thank you very much @JonathanMagnan . have a nice day BRO
